{
	"cloudflare_mesh_dns_updater_access_client_id": "ENC[AES256_GCM,data:H/l+ywDkCJKM62x2cRX2FQEqGIzBndFRH9w1HYQAVQ0AEjdQhsJW,iv:5kkwk92htr3ARLg7S86HEekw+YqJjBNbi+euPSWeUY0=,tag:1rbe2W8pQtC9OS/aD2Q+gg==,type:str]",
	"cloudflare_mesh_dns_updater_access_client_secret": "ENC[AES256_GCM,data:jWYZowQPeXUU1fz39q97WdZ8U4yUYsAtEVB1in0cuUtNBT2E0uFNz2N9Tk7VpmljdXE9m/Q8vs6aLZJRj6boaQ==,iv:tCwsQuMxZlHtcjg5LN5rB61X4QCXhn96tS1X4oi96nE=,tag:6F6f+RUzaTTjYrTaWCRVZQ==,type:str]",
	"cloudflare_mesh_dns_updater_endpoint": "ENC[AES256_GCM,data:O7e3uRVqSJZJfKO1rwfA8bM8BNqPvAtccPH7Zi2wWppJQm9J1cDHmCG5gQ==,iv:MkWGNAU3QHdJAQPbfOMHZ2CrW4PqJ8Ms2Fx2ulmRryk=,tag:dtEpKf4U4ucLigM25wSKWA==,type:str]",
	"sops": {
		"gcp_kms": [
			{
				"created_at": "2026-06-07T15:22:56Z",
				"enc": "CiQAMc4Bm/umyXDXkw8jbNQDOvMtfSpkPMlxxIA8AldLBcZOr2kSSQByr0nRLR+upw19X3JCEUlZ3DJS83FIW3gU1XxLJzMfdIWrDFBtchsNldxxckqYta04pp1tnjaeId662LuznibRFufrKJ2l9W8=",
				"resource_id": "projects/shiron-dev/locations/global/keyRings/sops/cryptoKeys/sops-key"
			}
		],
		"lastmodified": "2026-06-07T15:22:57Z",
		"mac": "ENC[AES256_GCM,data:pvUPY7OAs1vMrRgohLQzsCKm6NU0Yj5MdQvOmeefEZQqiaa6UUT6IWiGC1NdDD23re8GVDYc9n+8TLwRksuHBP5kNWu1Ki+desxmmpxW9L1esz2xR6nXH8ycjoEqonrm8Ylgt4p6ooxj+pX04vLIc0MAeyf3z/Wj9YEPGKt91fE=,iv:43olA3tD/ZtUcwevELsw7NLnOBn/soYyFAOe9pfLBbY=,tag:DdccFykAXzSHpol4jCv/Jg==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.1"
	}
}
