{
	"cloudflare_mesh_connector_token": "ENC[AES256_GCM,data:B4MrffcAt4wE9X6F1g6S9kIIvwssUCT56Sgj9sGQwH6227j1K6gtVlau5lrz24jFvhM8wB2Agf8gesOd+6OrXoW7TvHnS0MVzyq4AhCcwCYcsdIFF76lApFVMSudTTO/A1O8UwCGeLwOJ5pA5z4T59ooOILnUh3czG40VtGwzqwJmGROOwf/Slkeh2QaANF65CKPFBvV7Q43ZoWyDB3sc9sD8l9C2BftGoMzaNCThl00RqM0cEvPNdhfdPuhLJO8ILCiWP7AFKlCjtv57RgrlM6SHAS/m5PHqfuZk5KnQPIYKxcOI6cjewjk6esWH6ht,iv:D4Ul8ZpovQsHSY7PCgeHvIwmREejZkYPgb4W1I45Ros=,tag:UTFqernZly0bsndRMPTN/w==,type:str]",
	"sops": {
		"gcp_kms": [
			{
				"created_at": "2026-06-01T18:09:37Z",
				"enc": "CiQAMc4Bm9heXJPMEmepTtWv2LV3iCfkAKxl4qvaeul8F36ST9kSSQByr0nRhY/TlHTbj22ARp5NotXYpnrrdKrE06fkMXvNThoK4A7PHm0yHTpT9DRydkauKMvQpGpDFAN+MA0P5pheVEhPyM4nelI=",
				"resource_id": "projects/shiron-dev/locations/global/keyRings/sops/cryptoKeys/sops-key"
			}
		],
		"lastmodified": "2026-06-01T18:09:37Z",
		"mac": "ENC[AES256_GCM,data:VNc5FRTwUQ76pwN8TAHAKn1RSh42urFKMZg+tOvVhLQe43ipn94iIq73IagxdeZsgV0uQ52l04NNdGASjxKGHtJQghnBD7hdkAK+YCndVFMBxmMOYtOV5AdSduGCB5U2wHoUyKUQBI15zdK1eLIU5znCqbU+ICr3cHRn43uC8hM=,iv:6hyrRd9XLal8+7ECWlIffXaupvOUhyfTG1821DOVKVU=,tag:MwpuGUabzR5+A0hPJ1jEuA==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.0"
	}
}
