- light:
    # - name: "Color Bulbs Group"
    #   unique_id: color_bulbs_group
    #   state: >-
    #     {{"{{"}}
    #       is_state('light.color_bulb_13ce', 'on')
    #       or is_state('light.color_bulb_e1f6', 'on')
    #       or is_state('light.color_bulb_eb42', 'on')
    #     {{"}}"}}
    #   level: >-
    #     {{"{{"}} state_attr('light.color_bulb_13ce', 'brightness') {{"}}"}}
    #   rgb: >-
    #     {{"{{"}} state_attr('light.color_bulb_13ce', 'rgb_color') {{"}}"}}
    #   turn_on:
    #     - parallel:
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_13ce
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_e1f6
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_eb42
    #     - delay:
    #         milliseconds: 500
    #     - parallel:
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_13ce
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_e1f6
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_eb42
    #   turn_off:
    #     - parallel:
    #         - action: light.turn_off
    #           target:
    #             entity_id: light.color_bulb_13ce
    #         - action: light.turn_off
    #           target:
    #             entity_id: light.color_bulb_e1f6
    #         - action: light.turn_off
    #           target:
    #             entity_id: light.color_bulb_eb42
    #     - delay:
    #         milliseconds: 500
    #     - parallel:
    #         - action: light.turn_off
    #           target:
    #             entity_id: light.color_bulb_13ce
    #         - action: light.turn_off
    #           target:
    #             entity_id: light.color_bulb_e1f6
    #         - action: light.turn_off
    #           target:
    #             entity_id: light.color_bulb_eb42
    #   set_level:
    #     - parallel:
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_13ce
    #           data:
    #             brightness: >-
    #               {{"{{"}} brightness {{"}}"}}
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_e1f6
    #           data:
    #             brightness: >-
    #               {{"{{"}} brightness {{"}}"}}
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_eb42
    #           data:
    #             brightness: >-
    #               {{"{{"}} brightness {{"}}"}}
    #   set_rgb:
    #     - parallel:
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_13ce
    #           data:
    #             rgb_color: >-
    #               {{"{{"}} rgb {{"}}"}}
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_e1f6
    #           data:
    #             rgb_color: >-
    #               {{"{{"}} rgb {{"}}"}}
    #         - action: light.turn_on
    #           target:
    #             entity_id: light.color_bulb_eb42
    #           data:
    #             rgb_color: >-
    #               {{"{{"}} rgb {{"}}"}}

    - name: "Washroom Light"
      unique_id: washroom_light_template
      state: >-
        {{"{{"}} is_state('switch.washroom_light', 'on') {{"}}"}}
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.washroom_light
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.washroom_light

    - name: "Bathroom Light"
      unique_id: bathroom_light_template
      state: >-
        {{"{{"}} is_state('switch.bathroom_light', 'on') {{"}}"}}
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.bathroom_light
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.bathroom_light

    - name: "Toilet Light"
      unique_id: toilet_light_template
      state: >-
        {{"{{"}} is_state('switch.toilet_light', 'on') {{"}}"}}
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.toilet_light
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.toilet_light

    - name: "Hallway Light"
      unique_id: hallway_light_template
      state: >-
        {{"{{"}} is_state('switch.hallway_light', 'on') {{"}}"}}
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.hallway_light
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.hallway_light

    - name: "Kitchen Light"
      unique_id: kitchen_light_template
      state: >-
        {{"{{"}} is_state('switch.kitchen_light', 'on') {{"}}"}}
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.kitchen_light
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.kitchen_light

    - name: "Kitchen Sink Light"
      unique_id: kitchen_sink_light_template
      state: >-
        {{"{{"}} is_state('switch.sink_light', 'on') {{"}}"}}
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.sink_light
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.sink_light

- cover:
    - name: "Curtains"
      unique_id: curtains_template
      device_class: curtain
      availability: >-
        {{"{{"}}
          states('cover.main_curtain') not in ['unknown', 'unavailable']
          and states('cover.sub_curtain') not in ['unknown', 'unavailable']
        {{"}}"}}
      state: >-
        {{"{%"}} set main_state = states('cover.main_curtain') {{"%}"}}
        {{"{%"}} set sub_state = states('cover.sub_curtain') {{"%}"}}
        {{"{{"}}
          'opening' if main_state == 'opening' or sub_state == 'opening' else
          'closing' if main_state == 'closing' or sub_state == 'closing' else
          'closed' if main_state == 'closed' and sub_state == 'closed' else
          'open'
        {{"}}"}}
      position: >-
        {{"{{"}}
          (
            state_attr('cover.main_curtain', 'current_position') | int(0) +
            state_attr('cover.sub_curtain', 'current_position') | int(0)
          ) // 2
        {{"}}"}}
      open_cover:
        action: cover.open_cover
        target:
          entity_id:
            - cover.main_curtain
            - cover.sub_curtain
      close_cover:
        action: cover.close_cover
        target:
          entity_id:
            - cover.main_curtain
            - cover.sub_curtain
      stop_cover:
        action: cover.stop_cover
        target:
          entity_id:
            - cover.main_curtain
            - cover.sub_curtain
      set_cover_position:
        action: cover.set_cover_position
        target:
          entity_id:
            - cover.main_curtain
            - cover.sub_curtain
        data:
          position: >-
            {{"{{"}} position {{"}}"}}
