modules:
  cloudflare_tunnel_http_2xx:
    prober: http
    timeout: 10s
    http:
      method: GET
      preferred_ip_protocol: ip4
      headers:
        CF-Access-Client-Id: "{{ .cloudflare_access_e2e_client_id }}"
        CF-Access-Client-Secret: "{{ .cloudflare_access_e2e_client_secret }}"
  cloudflare_access_blocked_302:
    prober: http
    timeout: 10s
    http:
      method: GET
      preferred_ip_protocol: ip4
      follow_redirects: false
      valid_status_codes: [302]
      fail_if_header_not_matches:
        - header: Location
          regexp: '^https://[^/]+\.cloudflareaccess\.com/'
