global:
  scrape_interval: 15s
  external_labels:
    probe_server: 'arm-srv'
scrape_configs:
  - job_name: 'vmagent'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:8429']
  - job_name: 'node'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          host: arm-srv
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'docker_compose'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['docker_compose_exporter:9487']
  - job_name: 'cloudflare_tunnel_e2e'
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /probe
    params:
      module: [cloudflare_tunnel_http_2xx]
    static_configs:
      - targets:
          - https://grafana.shiron.dev/
          - https://n8n.shiron.dev/
          - https://snipeit.shiron.dev/
        labels:
          edge_auth: cloudflare_access
          target_server: arm-srv
      - targets:
          - https://home.melisia.net/
          - https://zigbee2mqtt.melisia.net/
          - https://switchbot-mqtt.melisia.net/
          - https://esphome.melisia.net/
        labels:
          edge_auth: cloudflare_access
          target_server: home-ep
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: 'https?://([^/:]+).*'
        target_label: host
        replacement: '$1'
      - target_label: __address__
        replacement: blackbox_exporter:9115
  - job_name: 'cloudflare_access_block_e2e'
    scrape_interval: 1h
    scrape_timeout: 15s
    metrics_path: /probe
    params:
      module: [cloudflare_access_blocked_302]
    static_configs:
      - targets:
          - https://grafana.shiron.dev/
          - https://n8n.shiron.dev/
          - https://snipeit.shiron.dev/
        labels:
          edge_auth: cloudflare_access_block
          target_server: arm-srv
      - targets:
          - https://zigbee2mqtt.melisia.net/
          - https://switchbot-mqtt.melisia.net/
          - https://esphome.melisia.net/
        labels:
          edge_auth: cloudflare_access_block
          target_server: home-ep
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: 'https?://([^/:]+).*'
        target_label: host
        replacement: '$1'
      - target_label: __address__
        replacement: blackbox_exporter:9115
