services:
  # kics-scan ignore-line
  promtail:
    container_name: home_ep_promtail
    image: grafana/promtail:3.5.0@sha256:507dfecd2f0949475d071c124bea1c26fc4f8c1cff0372eee57478d5b1c5fbff
    volumes:
      - "./promtail.yml:/etc/promtail/config.yml:ro"
      # kics-scan ignore-line
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # kics-scan ignore-line
      - "/var/log/journal:/var/log/journal:ro"
      # kics-scan ignore-line
      - "/run/log/journal:/run/log/journal:ro"
      # kics-scan ignore-line
      - "/etc/machine-id:/etc/machine-id:ro"
      - "./promtail_positions:/tmp/positions"
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M
