- name: Enable init_task
  become: true
  ansible.builtin.systemd:
    name: init_task
    enabled: true
    state: started
    daemon_reload: true
  notify: Reboot

- name: Restart journald
  become: true
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Reload NetworkManager connections
  become: true
  ansible.builtin.command:
    cmd: nmcli connection reload
  changed_when: false

- name: Reboot
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
