- name: enable init_task
  become: true
  ansible.builtin.systemd:
    name: init_task
    enabled: true
    state: started
    daemon_reload: true
  notify: reboot

- name: reload NetworkManager connections
  become: true
  ansible.builtin.command:
    cmd: nmcli connection reload

- name: reboot
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
