// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/shiron-dev/melisia/tools/cmt/internal/remote (interfaces: RemoteClient,ClientFactory,CommandRunner)
//
// Generated by this command:
//
//	mockgen -destination=mock_remote_interfaces.go -package=remote github.com/shiron-dev/melisia/tools/cmt/internal/remote RemoteClient,ClientFactory,CommandRunner
//

// Package remote is a generated GoMock package.
package remote

import (
	config "github.com/shiron-dev/melisia/tools/cmt/internal/config"
	fs "io/fs"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteClient is a mock of RemoteClient interface.
type MockRemoteClient struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteClientMockRecorder
	isgomock struct{}
}

// MockRemoteClientMockRecorder is the mock recorder for MockRemoteClient.
type MockRemoteClientMockRecorder struct {
	mock *MockRemoteClient
}

// NewMockRemoteClient creates a new mock instance.
func NewMockRemoteClient(ctrl *gomock.Controller) *MockRemoteClient {
	mock := &MockRemoteClient{ctrl: ctrl}
	mock.recorder = &MockRemoteClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteClient) EXPECT() *MockRemoteClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRemoteClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRemoteClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRemoteClient)(nil).Close))
}

// ListFilesRecursive mocks base method.
func (m *MockRemoteClient) ListFilesRecursive(dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesRecursive", dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesRecursive indicates an expected call of ListFilesRecursive.
func (mr *MockRemoteClientMockRecorder) ListFilesRecursive(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesRecursive", reflect.TypeOf((*MockRemoteClient)(nil).ListFilesRecursive), dir)
}

// MkdirAll mocks base method.
func (m *MockRemoteClient) MkdirAll(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockRemoteClientMockRecorder) MkdirAll(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockRemoteClient)(nil).MkdirAll), dir)
}

// ReadFile mocks base method.
func (m *MockRemoteClient) ReadFile(remotePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", remotePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockRemoteClientMockRecorder) ReadFile(remotePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockRemoteClient)(nil).ReadFile), remotePath)
}

// Remove mocks base method.
func (m *MockRemoteClient) Remove(remotePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", remotePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRemoteClientMockRecorder) Remove(remotePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRemoteClient)(nil).Remove), remotePath)
}

// RunCommand mocks base method.
func (m *MockRemoteClient) RunCommand(workdir, command string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCommand", workdir, command)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunCommand indicates an expected call of RunCommand.
func (mr *MockRemoteClientMockRecorder) RunCommand(workdir, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCommand", reflect.TypeOf((*MockRemoteClient)(nil).RunCommand), workdir, command)
}

// Stat mocks base method.
func (m *MockRemoteClient) Stat(remotePath string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", remotePath)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockRemoteClientMockRecorder) Stat(remotePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockRemoteClient)(nil).Stat), remotePath)
}

// StatDirMetadata mocks base method.
func (m *MockRemoteClient) StatDirMetadata(remotePath string) (*DirMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatDirMetadata", remotePath)
	ret0, _ := ret[0].(*DirMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatDirMetadata indicates an expected call of StatDirMetadata.
func (mr *MockRemoteClientMockRecorder) StatDirMetadata(remotePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatDirMetadata", reflect.TypeOf((*MockRemoteClient)(nil).StatDirMetadata), remotePath)
}

// WriteFile mocks base method.
func (m *MockRemoteClient) WriteFile(remotePath string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", remotePath, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockRemoteClientMockRecorder) WriteFile(remotePath, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockRemoteClient)(nil).WriteFile), remotePath, data)
}

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
	isgomock struct{}
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// NewClient mocks base method.
func (m *MockClientFactory) NewClient(entry config.HostEntry) (RemoteClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", entry)
	ret0, _ := ret[0].(RemoteClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockClientFactoryMockRecorder) NewClient(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockClientFactory)(nil).NewClient), entry)
}

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// SCPCombinedOutput mocks base method.
func (m *MockCommandRunner) SCPCombinedOutput(args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SCPCombinedOutput", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SCPCombinedOutput indicates an expected call of SCPCombinedOutput.
func (mr *MockCommandRunnerMockRecorder) SCPCombinedOutput(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SCPCombinedOutput", reflect.TypeOf((*MockCommandRunner)(nil).SCPCombinedOutput), args...)
}

// SSHCombinedOutput mocks base method.
func (m *MockCommandRunner) SSHCombinedOutput(args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SSHCombinedOutput", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SSHCombinedOutput indicates an expected call of SSHCombinedOutput.
func (mr *MockCommandRunnerMockRecorder) SSHCombinedOutput(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SSHCombinedOutput", reflect.TypeOf((*MockCommandRunner)(nil).SSHCombinedOutput), args...)
}
