# yaml-language-server: $schema=../tools/cmt/schemas/cmt-config.schema.json

basePath: .

beforeApplyHooks:
  beforeApplyPrompt:
    command: sh scripts/is-ci.sh

defaults:
  remotePath: /opt/compose
  composeAction: up

hosts:
  # - name: arm-srv
  #   host: arm-srv.shiron.dev
  #   user: ansible_user
  - name: home-ep
    host: home-ep
    user: ansible_user
