name: CMT Plan CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cmt-plan-status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: No-op cmt plan status check
        run: echo "cmt plan is disabled."
