name: Terraform Plan CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  terraform-plan-status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: No-op terraform plan status check
        run: echo "terraform plan is disabled."
